apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eyupyayan/Devops-Pipeline-Project.git
    targetRevision: master
    path: argocd
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-dev
  syncPolicy:
    automated:
      prune: true

      selfHeal: true

